# -*- coding: utf-8 -*-
"""PS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJHv9I3AQ-BtUmoz4D2bJ0rCjJLwIntu
"""

def bubble_sort_priority(processes):
    n = len(processes)
    for i in range(n):
        for j in range(0, n-i-1):
            # Sort by priority (index 2)
            if processes[j][2] > processes[j+1][2]:
                processes[j], processes[j+1] = processes[j+1], processes[j]

def priority_scheduling(processes):
    # processes = [(process_id, burst_time, priority), ...]
    bubble_sort_priority(processes)

    current_time = 0
    gantt_chart = []
    waiting_times = []

    for process_id, burst_time, priority in processes:
        waiting_time = current_time
        waiting_times.append(waiting_time)

        gantt_chart.append(f'{current_time} {process_id}')
        current_time += burst_time

    gantt_chart.append(f'{current_time}')

    avg_waiting_time = sum(waiting_times) / len(processes)
    gantt_chart_str = " ".join(gantt_chart)

    return gantt_chart_str, avg_waiting_time


# Example usage:
processes = [('p1', 21, 2), ('p2', 3, 1), ('p3', 6, 4), ('p4', 2, 3)]
gantt_chart, avg_wt = priority_scheduling(processes)

print("Gantt Chart:", gantt_chart)
print(f"Average Waiting Time: {avg_wt:.2f}")